services:
  - type: web
    name: it-helpdesk-simulator
    runtime: python
    buildCommand: "./build.sh"
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: it-helpdesk-db
          property: connectionString

databases:
  - name: it-helpdesk-db
    plan: free
